name: V Compiler Status

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup V
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true

      - name: Go into Source dir
        run: cd src

      - name: Compile project
        run: (cd src && v .)
