name: V Compiler Status

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            cmake \
            build-essential \
            liblua5.4-dev \
            libasound2-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxcursor-dev \
            libxinerama-dev
      
      - name: Install Raylib
        run: |
          git clone --depth 1 --branch 5.0 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install
          sudo ldconfig


      - name: Setup V 0.5.1
        run: |
          curl -fsSL \
            https://github.com/vlang/v/releases/download/0.5.1/v_linux.zip \
            -o v_linux.zip
          unzip -q v_linux.zip
          echo "$PWD/v" >> "$GITHUB_PATH"

      - name: Verify V
        run: |
          v version

      - name: Compile project
        run: (cd src && v install && v .)
